/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the AddressAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddressAllOf{}

// AddressAllOf struct for AddressAllOf
type AddressAllOf struct {
	Balance *string  `json:"balance,omitempty"`
	Chain   string   `json:"chain"`
	Modules []string `json:"modules"`
	// The next transaction nonce for this address (obtained from the blockchain node).
	Nonce *int64 `json:"nonce,omitempty"`
	// The next transaction nonce for this address when using the nonce management feature.
	LocalNonce *int64             `json:"localNonce,omitempty"`
	CodeAt     *string            `json:"codeAt,omitempty"`
	Contracts  []ContractMetadata `json:"contracts"`
}

// NewAddressAllOf instantiates a new AddressAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressAllOf(chain string, modules []string, contracts []ContractMetadata) *AddressAllOf {
	this := AddressAllOf{}
	this.Chain = chain
	this.Modules = modules
	this.Contracts = contracts
	return &this
}

// NewAddressAllOfWithDefaults instantiates a new AddressAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressAllOfWithDefaults() *AddressAllOf {
	this := AddressAllOf{}
	return &this
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *AddressAllOf) GetBalance() string {
	if o == nil || IsNil(o.Balance) {
		var ret string
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressAllOf) GetBalanceOk() (*string, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *AddressAllOf) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given string and assigns it to the Balance field.
func (o *AddressAllOf) SetBalance(v string) {
	o.Balance = &v
}

// GetChain returns the Chain field value
func (o *AddressAllOf) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *AddressAllOf) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *AddressAllOf) SetChain(v string) {
	o.Chain = v
}

// GetModules returns the Modules field value
func (o *AddressAllOf) GetModules() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Modules
}

// GetModulesOk returns a tuple with the Modules field value
// and a boolean to check if the value has been set.
func (o *AddressAllOf) GetModulesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Modules, true
}

// SetModules sets field value
func (o *AddressAllOf) SetModules(v []string) {
	o.Modules = v
}

// GetNonce returns the Nonce field value if set, zero value otherwise.
func (o *AddressAllOf) GetNonce() int64 {
	if o == nil || IsNil(o.Nonce) {
		var ret int64
		return ret
	}
	return *o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressAllOf) GetNonceOk() (*int64, bool) {
	if o == nil || IsNil(o.Nonce) {
		return nil, false
	}
	return o.Nonce, true
}

// HasNonce returns a boolean if a field has been set.
func (o *AddressAllOf) HasNonce() bool {
	if o != nil && !IsNil(o.Nonce) {
		return true
	}

	return false
}

// SetNonce gets a reference to the given int64 and assigns it to the Nonce field.
func (o *AddressAllOf) SetNonce(v int64) {
	o.Nonce = &v
}

// GetLocalNonce returns the LocalNonce field value if set, zero value otherwise.
func (o *AddressAllOf) GetLocalNonce() int64 {
	if o == nil || IsNil(o.LocalNonce) {
		var ret int64
		return ret
	}
	return *o.LocalNonce
}

// GetLocalNonceOk returns a tuple with the LocalNonce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressAllOf) GetLocalNonceOk() (*int64, bool) {
	if o == nil || IsNil(o.LocalNonce) {
		return nil, false
	}
	return o.LocalNonce, true
}

// HasLocalNonce returns a boolean if a field has been set.
func (o *AddressAllOf) HasLocalNonce() bool {
	if o != nil && !IsNil(o.LocalNonce) {
		return true
	}

	return false
}

// SetLocalNonce gets a reference to the given int64 and assigns it to the LocalNonce field.
func (o *AddressAllOf) SetLocalNonce(v int64) {
	o.LocalNonce = &v
}

// GetCodeAt returns the CodeAt field value if set, zero value otherwise.
func (o *AddressAllOf) GetCodeAt() string {
	if o == nil || IsNil(o.CodeAt) {
		var ret string
		return ret
	}
	return *o.CodeAt
}

// GetCodeAtOk returns a tuple with the CodeAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddressAllOf) GetCodeAtOk() (*string, bool) {
	if o == nil || IsNil(o.CodeAt) {
		return nil, false
	}
	return o.CodeAt, true
}

// HasCodeAt returns a boolean if a field has been set.
func (o *AddressAllOf) HasCodeAt() bool {
	if o != nil && !IsNil(o.CodeAt) {
		return true
	}

	return false
}

// SetCodeAt gets a reference to the given string and assigns it to the CodeAt field.
func (o *AddressAllOf) SetCodeAt(v string) {
	o.CodeAt = &v
}

// GetContracts returns the Contracts field value
func (o *AddressAllOf) GetContracts() []ContractMetadata {
	if o == nil {
		var ret []ContractMetadata
		return ret
	}

	return o.Contracts
}

// GetContractsOk returns a tuple with the Contracts field value
// and a boolean to check if the value has been set.
func (o *AddressAllOf) GetContractsOk() ([]ContractMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contracts, true
}

// SetContracts sets field value
func (o *AddressAllOf) SetContracts(v []ContractMetadata) {
	o.Contracts = v
}

func (o AddressAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddressAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	toSerialize["chain"] = o.Chain
	toSerialize["modules"] = o.Modules
	if !IsNil(o.Nonce) {
		toSerialize["nonce"] = o.Nonce
	}
	if !IsNil(o.LocalNonce) {
		toSerialize["localNonce"] = o.LocalNonce
	}
	if !IsNil(o.CodeAt) {
		toSerialize["codeAt"] = o.CodeAt
	}
	toSerialize["contracts"] = o.Contracts
	return toSerialize, nil
}

type NullableAddressAllOf struct {
	value *AddressAllOf
	isSet bool
}

func (v NullableAddressAllOf) Get() *AddressAllOf {
	return v.value
}

func (v *NullableAddressAllOf) Set(val *AddressAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressAllOf(val *AddressAllOf) *NullableAddressAllOf {
	return &NullableAddressAllOf{value: val, isSet: true}
}

func (v NullableAddressAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
