/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the DeployContract200ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeployContract200ResponseAllOf{}

// DeployContract200ResponseAllOf struct for DeployContract200ResponseAllOf
type DeployContract200ResponseAllOf struct {
	Result DeployContractTransaction `json:"result"`
}

// NewDeployContract200ResponseAllOf instantiates a new DeployContract200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeployContract200ResponseAllOf(result DeployContractTransaction) *DeployContract200ResponseAllOf {
	this := DeployContract200ResponseAllOf{}
	this.Result = result
	return &this
}

// NewDeployContract200ResponseAllOfWithDefaults instantiates a new DeployContract200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeployContract200ResponseAllOfWithDefaults() *DeployContract200ResponseAllOf {
	this := DeployContract200ResponseAllOf{}
	return &this
}

// GetResult returns the Result field value
func (o *DeployContract200ResponseAllOf) GetResult() DeployContractTransaction {
	if o == nil {
		var ret DeployContractTransaction
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *DeployContract200ResponseAllOf) GetResultOk() (*DeployContractTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *DeployContract200ResponseAllOf) SetResult(v DeployContractTransaction) {
	o.Result = v
}

func (o DeployContract200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeployContract200ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableDeployContract200ResponseAllOf struct {
	value *DeployContract200ResponseAllOf
	isSet bool
}

func (v NullableDeployContract200ResponseAllOf) Get() *DeployContract200ResponseAllOf {
	return v.value
}

func (v *NullableDeployContract200ResponseAllOf) Set(val *DeployContract200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDeployContract200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDeployContract200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeployContract200ResponseAllOf(val *DeployContract200ResponseAllOf) *NullableDeployContract200ResponseAllOf {
	return &NullableDeployContract200ResponseAllOf{value: val, isSet: true}
}

func (v NullableDeployContract200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeployContract200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
