/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the TransferEth200ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferEth200ResponseAllOf{}

// TransferEth200ResponseAllOf struct for TransferEth200ResponseAllOf
type TransferEth200ResponseAllOf struct {
	Result TransactionToSign `json:"result"`
}

// NewTransferEth200ResponseAllOf instantiates a new TransferEth200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferEth200ResponseAllOf(result TransactionToSign) *TransferEth200ResponseAllOf {
	this := TransferEth200ResponseAllOf{}
	this.Result = result
	return &this
}

// NewTransferEth200ResponseAllOfWithDefaults instantiates a new TransferEth200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferEth200ResponseAllOfWithDefaults() *TransferEth200ResponseAllOf {
	this := TransferEth200ResponseAllOf{}
	return &this
}

// GetResult returns the Result field value
func (o *TransferEth200ResponseAllOf) GetResult() TransactionToSign {
	if o == nil {
		var ret TransactionToSign
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *TransferEth200ResponseAllOf) GetResultOk() (*TransactionToSign, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *TransferEth200ResponseAllOf) SetResult(v TransactionToSign) {
	o.Result = v
}

func (o TransferEth200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferEth200ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableTransferEth200ResponseAllOf struct {
	value *TransferEth200ResponseAllOf
	isSet bool
}

func (v NullableTransferEth200ResponseAllOf) Get() *TransferEth200ResponseAllOf {
	return v.value
}

func (v *NullableTransferEth200ResponseAllOf) Set(val *TransferEth200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferEth200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferEth200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferEth200ResponseAllOf(val *TransferEth200ResponseAllOf) *NullableTransferEth200ResponseAllOf {
	return &NullableTransferEth200ResponseAllOf{value: val, isSet: true}
}

func (v NullableTransferEth200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferEth200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
