/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetFunctionTypeConversions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFunctionTypeConversions200Response{}

// GetFunctionTypeConversions200Response struct for GetFunctionTypeConversions200Response
type GetFunctionTypeConversions200Response struct {
	// The status code.
	Status int64 `json:"status"`
	// The human-readable status message.
	Message string                      `json:"message"`
	Result  MethodTypeConversionOptions `json:"result"`
}

type _GetFunctionTypeConversions200Response GetFunctionTypeConversions200Response

// NewGetFunctionTypeConversions200Response instantiates a new GetFunctionTypeConversions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFunctionTypeConversions200Response(status int64, message string, result MethodTypeConversionOptions) *GetFunctionTypeConversions200Response {
	this := GetFunctionTypeConversions200Response{}
	this.Status = status
	this.Message = message
	this.Result = result
	return &this
}

// NewGetFunctionTypeConversions200ResponseWithDefaults instantiates a new GetFunctionTypeConversions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFunctionTypeConversions200ResponseWithDefaults() *GetFunctionTypeConversions200Response {
	this := GetFunctionTypeConversions200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *GetFunctionTypeConversions200Response) GetStatus() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetFunctionTypeConversions200Response) GetStatusOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetFunctionTypeConversions200Response) SetStatus(v int64) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *GetFunctionTypeConversions200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GetFunctionTypeConversions200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GetFunctionTypeConversions200Response) SetMessage(v string) {
	o.Message = v
}

// GetResult returns the Result field value
func (o *GetFunctionTypeConversions200Response) GetResult() MethodTypeConversionOptions {
	if o == nil {
		var ret MethodTypeConversionOptions
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *GetFunctionTypeConversions200Response) GetResultOk() (*MethodTypeConversionOptions, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *GetFunctionTypeConversions200Response) SetResult(v MethodTypeConversionOptions) {
	o.Result = v
}

func (o GetFunctionTypeConversions200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFunctionTypeConversions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *GetFunctionTypeConversions200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"message",
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetFunctionTypeConversions200Response := _GetFunctionTypeConversions200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetFunctionTypeConversions200Response)

	if err != nil {
		return err
	}

	*o = GetFunctionTypeConversions200Response(varGetFunctionTypeConversions200Response)

	return err
}

type NullableGetFunctionTypeConversions200Response struct {
	value *GetFunctionTypeConversions200Response
	isSet bool
}

func (v NullableGetFunctionTypeConversions200Response) Get() *GetFunctionTypeConversions200Response {
	return v.value
}

func (v *NullableGetFunctionTypeConversions200Response) Set(val *GetFunctionTypeConversions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFunctionTypeConversions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFunctionTypeConversions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFunctionTypeConversions200Response(val *GetFunctionTypeConversions200Response) *NullableGetFunctionTypeConversions200Response {
	return &NullableGetFunctionTypeConversions200Response{value: val, isSet: true}
}

func (v NullableGetFunctionTypeConversions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFunctionTypeConversions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
