/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the CreateWebhook200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWebhook200Response{}

// CreateWebhook200Response struct for CreateWebhook200Response
type CreateWebhook200Response struct {
	// The status code.
	Status int64 `json:"status"`
	// The human-readable status message.
	Message string          `json:"message"`
	Result  WebhookEndpoint `json:"result"`
}

type _CreateWebhook200Response CreateWebhook200Response

// NewCreateWebhook200Response instantiates a new CreateWebhook200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWebhook200Response(status int64, message string, result WebhookEndpoint) *CreateWebhook200Response {
	this := CreateWebhook200Response{}
	this.Status = status
	this.Message = message
	this.Result = result
	return &this
}

// NewCreateWebhook200ResponseWithDefaults instantiates a new CreateWebhook200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWebhook200ResponseWithDefaults() *CreateWebhook200Response {
	this := CreateWebhook200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *CreateWebhook200Response) GetStatus() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateWebhook200Response) GetStatusOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateWebhook200Response) SetStatus(v int64) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *CreateWebhook200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CreateWebhook200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CreateWebhook200Response) SetMessage(v string) {
	o.Message = v
}

// GetResult returns the Result field value
func (o *CreateWebhook200Response) GetResult() WebhookEndpoint {
	if o == nil {
		var ret WebhookEndpoint
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *CreateWebhook200Response) GetResultOk() (*WebhookEndpoint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *CreateWebhook200Response) SetResult(v WebhookEndpoint) {
	o.Result = v
}

func (o CreateWebhook200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableCreateWebhook200Response struct {
	value *CreateWebhook200Response
	isSet bool
}

func (v NullableCreateWebhook200Response) Get() *CreateWebhook200Response {
	return v.value
}

func (v *NullableCreateWebhook200Response) Set(val *CreateWebhook200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWebhook200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWebhook200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWebhook200Response(val *CreateWebhook200Response) *NullableCreateWebhook200Response {
	return &NullableCreateWebhook200Response{value: val, isSet: true}
}

func (v NullableCreateWebhook200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWebhook200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
