/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the ListAddresses200ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAddresses200ResponseAllOf{}

// ListAddresses200ResponseAllOf struct for ListAddresses200ResponseAllOf
type ListAddresses200ResponseAllOf struct {
	Result []AddressLabel `json:"result"`
}

// NewListAddresses200ResponseAllOf instantiates a new ListAddresses200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAddresses200ResponseAllOf(result []AddressLabel) *ListAddresses200ResponseAllOf {
	this := ListAddresses200ResponseAllOf{}
	this.Result = result
	return &this
}

// NewListAddresses200ResponseAllOfWithDefaults instantiates a new ListAddresses200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAddresses200ResponseAllOfWithDefaults() *ListAddresses200ResponseAllOf {
	this := ListAddresses200ResponseAllOf{}
	return &this
}

// GetResult returns the Result field value
func (o *ListAddresses200ResponseAllOf) GetResult() []AddressLabel {
	if o == nil {
		var ret []AddressLabel
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ListAddresses200ResponseAllOf) GetResultOk() ([]AddressLabel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *ListAddresses200ResponseAllOf) SetResult(v []AddressLabel) {
	o.Result = v
}

func (o ListAddresses200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAddresses200ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableListAddresses200ResponseAllOf struct {
	value *ListAddresses200ResponseAllOf
	isSet bool
}

func (v NullableListAddresses200ResponseAllOf) Get() *ListAddresses200ResponseAllOf {
	return v.value
}

func (v *NullableListAddresses200ResponseAllOf) Set(val *ListAddresses200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableListAddresses200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableListAddresses200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAddresses200ResponseAllOf(val *ListAddresses200ResponseAllOf) *NullableListAddresses200ResponseAllOf {
	return &NullableListAddresses200ResponseAllOf{value: val, isSet: true}
}

func (v NullableListAddresses200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAddresses200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
