/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the ListEventQueries200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEventQueries200Response{}

// ListEventQueries200Response struct for ListEventQueries200Response
type ListEventQueries200Response struct {
	// The status code.
	Status int64 `json:"status"`
	// The human-readable status message.
	Message string            `json:"message"`
	Result  []SavedEventQuery `json:"result"`
}

// NewListEventQueries200Response instantiates a new ListEventQueries200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEventQueries200Response(status int64, message string, result []SavedEventQuery) *ListEventQueries200Response {
	this := ListEventQueries200Response{}
	this.Status = status
	this.Message = message
	this.Result = result
	return &this
}

// NewListEventQueries200ResponseWithDefaults instantiates a new ListEventQueries200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEventQueries200ResponseWithDefaults() *ListEventQueries200Response {
	this := ListEventQueries200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *ListEventQueries200Response) GetStatus() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ListEventQueries200Response) GetStatusOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ListEventQueries200Response) SetStatus(v int64) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *ListEventQueries200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ListEventQueries200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ListEventQueries200Response) SetMessage(v string) {
	o.Message = v
}

// GetResult returns the Result field value
func (o *ListEventQueries200Response) GetResult() []SavedEventQuery {
	if o == nil {
		var ret []SavedEventQuery
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ListEventQueries200Response) GetResultOk() ([]SavedEventQuery, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *ListEventQueries200Response) SetResult(v []SavedEventQuery) {
	o.Result = v
}

func (o ListEventQueries200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEventQueries200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableListEventQueries200Response struct {
	value *ListEventQueries200Response
	isSet bool
}

func (v NullableListEventQueries200Response) Get() *ListEventQueries200Response {
	return v.value
}

func (v *NullableListEventQueries200Response) Set(val *ListEventQueries200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListEventQueries200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListEventQueries200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEventQueries200Response(val *ListEventQueries200Response) *NullableListEventQueries200Response {
	return &NullableListEventQueries200Response{value: val, isSet: true}
}

func (v NullableListEventQueries200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEventQueries200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
