/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the ListAuditLogs200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAuditLogs200Response{}

// ListAuditLogs200Response struct for ListAuditLogs200Response
type ListAuditLogs200Response struct {
	// The status code.
	Status int64 `json:"status"`
	// The human-readable status message.
	Message string     `json:"message"`
	Result  []AuditLog `json:"result"`
}

type _ListAuditLogs200Response ListAuditLogs200Response

// NewListAuditLogs200Response instantiates a new ListAuditLogs200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAuditLogs200Response(status int64, message string, result []AuditLog) *ListAuditLogs200Response {
	this := ListAuditLogs200Response{}
	this.Status = status
	this.Message = message
	this.Result = result
	return &this
}

// NewListAuditLogs200ResponseWithDefaults instantiates a new ListAuditLogs200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAuditLogs200ResponseWithDefaults() *ListAuditLogs200Response {
	this := ListAuditLogs200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *ListAuditLogs200Response) GetStatus() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ListAuditLogs200Response) GetStatusOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ListAuditLogs200Response) SetStatus(v int64) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *ListAuditLogs200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ListAuditLogs200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ListAuditLogs200Response) SetMessage(v string) {
	o.Message = v
}

// GetResult returns the Result field value
func (o *ListAuditLogs200Response) GetResult() []AuditLog {
	if o == nil {
		var ret []AuditLog
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ListAuditLogs200Response) GetResultOk() ([]AuditLog, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *ListAuditLogs200Response) SetResult(v []AuditLog) {
	o.Result = v
}

func (o ListAuditLogs200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableListAuditLogs200Response struct {
	value *ListAuditLogs200Response
	isSet bool
}

func (v NullableListAuditLogs200Response) Get() *ListAuditLogs200Response {
	return v.value
}

func (v *NullableListAuditLogs200Response) Set(val *ListAuditLogs200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAuditLogs200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAuditLogs200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAuditLogs200Response(val *ListAuditLogs200Response) *NullableListAuditLogs200Response {
	return &NullableListAuditLogs200Response{value: val, isSet: true}
}

func (v NullableListAuditLogs200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAuditLogs200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
