/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the MethodCallResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MethodCallResponseAllOf{}

// MethodCallResponseAllOf struct for MethodCallResponseAllOf
type MethodCallResponseAllOf struct {
	// The function call output.
	Output interface{} `json:"output"`
}

// NewMethodCallResponseAllOf instantiates a new MethodCallResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMethodCallResponseAllOf(output interface{}) *MethodCallResponseAllOf {
	this := MethodCallResponseAllOf{}
	this.Output = output
	return &this
}

// NewMethodCallResponseAllOfWithDefaults instantiates a new MethodCallResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMethodCallResponseAllOfWithDefaults() *MethodCallResponseAllOf {
	this := MethodCallResponseAllOf{}
	return &this
}

// GetOutput returns the Output field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *MethodCallResponseAllOf) GetOutput() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Output
}

// GetOutputOk returns a tuple with the Output field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MethodCallResponseAllOf) GetOutputOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Output) {
		return nil, false
	}
	return &o.Output, true
}

// SetOutput sets field value
func (o *MethodCallResponseAllOf) SetOutput(v interface{}) {
	o.Output = v
}

func (o MethodCallResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MethodCallResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Output != nil {
		toSerialize["output"] = o.Output
	}
	return toSerialize, nil
}

type NullableMethodCallResponseAllOf struct {
	value *MethodCallResponseAllOf
	isSet bool
}

func (v NullableMethodCallResponseAllOf) Get() *MethodCallResponseAllOf {
	return v.value
}

func (v *NullableMethodCallResponseAllOf) Set(val *MethodCallResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableMethodCallResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableMethodCallResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMethodCallResponseAllOf(val *MethodCallResponseAllOf) *NullableMethodCallResponseAllOf {
	return &NullableMethodCallResponseAllOf{value: val, isSet: true}
}

func (v NullableMethodCallResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMethodCallResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
