/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the ListWalletTransactions200ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWalletTransactions200ResponseAllOf{}

// ListWalletTransactions200ResponseAllOf struct for ListWalletTransactions200ResponseAllOf
type ListWalletTransactions200ResponseAllOf struct {
	Result []WalletTransaction `json:"result"`
}

// NewListWalletTransactions200ResponseAllOf instantiates a new ListWalletTransactions200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWalletTransactions200ResponseAllOf(result []WalletTransaction) *ListWalletTransactions200ResponseAllOf {
	this := ListWalletTransactions200ResponseAllOf{}
	this.Result = result
	return &this
}

// NewListWalletTransactions200ResponseAllOfWithDefaults instantiates a new ListWalletTransactions200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWalletTransactions200ResponseAllOfWithDefaults() *ListWalletTransactions200ResponseAllOf {
	this := ListWalletTransactions200ResponseAllOf{}
	return &this
}

// GetResult returns the Result field value
func (o *ListWalletTransactions200ResponseAllOf) GetResult() []WalletTransaction {
	if o == nil {
		var ret []WalletTransaction
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ListWalletTransactions200ResponseAllOf) GetResultOk() ([]WalletTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *ListWalletTransactions200ResponseAllOf) SetResult(v []WalletTransaction) {
	o.Result = v
}

func (o ListWalletTransactions200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWalletTransactions200ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableListWalletTransactions200ResponseAllOf struct {
	value *ListWalletTransactions200ResponseAllOf
	isSet bool
}

func (v NullableListWalletTransactions200ResponseAllOf) Get() *ListWalletTransactions200ResponseAllOf {
	return v.value
}

func (v *NullableListWalletTransactions200ResponseAllOf) Set(val *ListWalletTransactions200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableListWalletTransactions200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableListWalletTransactions200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWalletTransactions200ResponseAllOf(val *ListWalletTransactions200ResponseAllOf) *NullableListWalletTransactions200ResponseAllOf {
	return &NullableListWalletTransactions200ResponseAllOf{value: val, isSet: true}
}

func (v NullableListWalletTransactions200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWalletTransactions200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
