/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the ListHsm200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListHsm200Response{}

// ListHsm200Response struct for ListHsm200Response
type ListHsm200Response struct {
	// The status code.
	Status int64 `json:"status"`
	// The human-readable status message.
	Message string    `json:"message"`
	Result  []HSMData `json:"result"`
}

type _ListHsm200Response ListHsm200Response

// NewListHsm200Response instantiates a new ListHsm200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListHsm200Response(status int64, message string, result []HSMData) *ListHsm200Response {
	this := ListHsm200Response{}
	this.Status = status
	this.Message = message
	this.Result = result
	return &this
}

// NewListHsm200ResponseWithDefaults instantiates a new ListHsm200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListHsm200ResponseWithDefaults() *ListHsm200Response {
	this := ListHsm200Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *ListHsm200Response) GetStatus() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ListHsm200Response) GetStatusOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ListHsm200Response) SetStatus(v int64) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *ListHsm200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ListHsm200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ListHsm200Response) SetMessage(v string) {
	o.Message = v
}

// GetResult returns the Result field value
func (o *ListHsm200Response) GetResult() []HSMData {
	if o == nil {
		var ret []HSMData
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *ListHsm200Response) GetResultOk() ([]HSMData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *ListHsm200Response) SetResult(v []HSMData) {
	o.Result = v
}

func (o ListHsm200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableListHsm200Response struct {
	value *ListHsm200Response
	isSet bool
}

func (v NullableListHsm200Response) Get() *ListHsm200Response {
	return v.value
}

func (v *NullableListHsm200Response) Set(val *ListHsm200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListHsm200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListHsm200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListHsm200Response(val *ListHsm200Response) *NullableListHsm200Response {
	return &NullableListHsm200Response{value: val, isSet: true}
}

func (v NullableListHsm200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListHsm200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
