/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the SetAddress201ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetAddress201ResponseAllOf{}

// SetAddress201ResponseAllOf struct for SetAddress201ResponseAllOf
type SetAddress201ResponseAllOf struct {
	Result Address `json:"result"`
}

// NewSetAddress201ResponseAllOf instantiates a new SetAddress201ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetAddress201ResponseAllOf(result Address) *SetAddress201ResponseAllOf {
	this := SetAddress201ResponseAllOf{}
	this.Result = result
	return &this
}

// NewSetAddress201ResponseAllOfWithDefaults instantiates a new SetAddress201ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetAddress201ResponseAllOfWithDefaults() *SetAddress201ResponseAllOf {
	this := SetAddress201ResponseAllOf{}
	return &this
}

// GetResult returns the Result field value
func (o *SetAddress201ResponseAllOf) GetResult() Address {
	if o == nil {
		var ret Address
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *SetAddress201ResponseAllOf) GetResultOk() (*Address, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *SetAddress201ResponseAllOf) SetResult(v Address) {
	o.Result = v
}

func (o SetAddress201ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetAddress201ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

type NullableSetAddress201ResponseAllOf struct {
	value *SetAddress201ResponseAllOf
	isSet bool
}

func (v NullableSetAddress201ResponseAllOf) Get() *SetAddress201ResponseAllOf {
	return v.value
}

func (v *NullableSetAddress201ResponseAllOf) Set(val *SetAddress201ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSetAddress201ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSetAddress201ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetAddress201ResponseAllOf(val *SetAddress201ResponseAllOf) *NullableSetAddress201ResponseAllOf {
	return &NullableSetAddress201ResponseAllOf{value: val, isSet: true}
}

func (v NullableSetAddress201ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetAddress201ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
