/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the TypeConversionOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypeConversionOptions{}

// TypeConversionOptions Represents the set of type conversions allowed for a particular input or output of a function (how it may be \"cast\").
type TypeConversionOptions struct {
	Types []string `json:"types,omitempty"`
}

// NewTypeConversionOptions instantiates a new TypeConversionOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypeConversionOptions() *TypeConversionOptions {
	this := TypeConversionOptions{}
	return &this
}

// NewTypeConversionOptionsWithDefaults instantiates a new TypeConversionOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypeConversionOptionsWithDefaults() *TypeConversionOptions {
	this := TypeConversionOptions{}
	return &this
}

// GetTypes returns the Types field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TypeConversionOptions) GetTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Types
}

// GetTypesOk returns a tuple with the Types field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TypeConversionOptions) GetTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.Types) {
		return nil, false
	}
	return o.Types, true
}

// HasTypes returns a boolean if a field has been set.
func (o *TypeConversionOptions) HasTypes() bool {
	if o != nil && IsNil(o.Types) {
		return true
	}

	return false
}

// SetTypes gets a reference to the given []string and assigns it to the Types field.
func (o *TypeConversionOptions) SetTypes(v []string) {
	o.Types = v
}

func (o TypeConversionOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypeConversionOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Types != nil {
		toSerialize["types"] = o.Types
	}
	return toSerialize, nil
}

type NullableTypeConversionOptions struct {
	value *TypeConversionOptions
	isSet bool
}

func (v NullableTypeConversionOptions) Get() *TypeConversionOptions {
	return v.value
}

func (v *NullableTypeConversionOptions) Set(val *TypeConversionOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableTypeConversionOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableTypeConversionOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypeConversionOptions(val *TypeConversionOptions) *NullableTypeConversionOptions {
	return &NullableTypeConversionOptions{value: val, isSet: true}
}

func (v NullableTypeConversionOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypeConversionOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
