/*
MultiBaas API

MultiBaas's REST APIv0.

API version: 0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package multibaas

import (
	"encoding/json"
)

// checks if the AzureAccountConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureAccountConfig{}

// AzureAccountConfig Add Config request data.
type AzureAccountConfig struct {
	// The Application ID that will be accessing the Key Vault.
	ClientID string `json:"clientID"`
	// The application’s secret key that you generate when you first register the application in Azure.
	ClientSecret string `json:"clientSecret"`
	// Also known as Directory ID.
	TenantID string `json:"tenantID"`
	// The ID linked to your subscription to Azure services.
	SubscriptionID string `json:"subscriptionID"`
	// The Resource Group Name for the resource being accessed.
	BaseGroupName string `json:"baseGroupName"`
}

// NewAzureAccountConfig instantiates a new AzureAccountConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureAccountConfig(clientID string, clientSecret string, tenantID string, subscriptionID string, baseGroupName string) *AzureAccountConfig {
	this := AzureAccountConfig{}
	this.ClientID = clientID
	this.ClientSecret = clientSecret
	this.TenantID = tenantID
	this.SubscriptionID = subscriptionID
	this.BaseGroupName = baseGroupName
	return &this
}

// NewAzureAccountConfigWithDefaults instantiates a new AzureAccountConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureAccountConfigWithDefaults() *AzureAccountConfig {
	this := AzureAccountConfig{}
	return &this
}

// GetClientID returns the ClientID field value
func (o *AzureAccountConfig) GetClientID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientID
}

// GetClientIDOk returns a tuple with the ClientID field value
// and a boolean to check if the value has been set.
func (o *AzureAccountConfig) GetClientIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientID, true
}

// SetClientID sets field value
func (o *AzureAccountConfig) SetClientID(v string) {
	o.ClientID = v
}

// GetClientSecret returns the ClientSecret field value
func (o *AzureAccountConfig) GetClientSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
func (o *AzureAccountConfig) GetClientSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *AzureAccountConfig) SetClientSecret(v string) {
	o.ClientSecret = v
}

// GetTenantID returns the TenantID field value
func (o *AzureAccountConfig) GetTenantID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantID
}

// GetTenantIDOk returns a tuple with the TenantID field value
// and a boolean to check if the value has been set.
func (o *AzureAccountConfig) GetTenantIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantID, true
}

// SetTenantID sets field value
func (o *AzureAccountConfig) SetTenantID(v string) {
	o.TenantID = v
}

// GetSubscriptionID returns the SubscriptionID field value
func (o *AzureAccountConfig) GetSubscriptionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionID
}

// GetSubscriptionIDOk returns a tuple with the SubscriptionID field value
// and a boolean to check if the value has been set.
func (o *AzureAccountConfig) GetSubscriptionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionID, true
}

// SetSubscriptionID sets field value
func (o *AzureAccountConfig) SetSubscriptionID(v string) {
	o.SubscriptionID = v
}

// GetBaseGroupName returns the BaseGroupName field value
func (o *AzureAccountConfig) GetBaseGroupName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseGroupName
}

// GetBaseGroupNameOk returns a tuple with the BaseGroupName field value
// and a boolean to check if the value has been set.
func (o *AzureAccountConfig) GetBaseGroupNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseGroupName, true
}

// SetBaseGroupName sets field value
func (o *AzureAccountConfig) SetBaseGroupName(v string) {
	o.BaseGroupName = v
}

func (o AzureAccountConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureAccountConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clientID"] = o.ClientID
	toSerialize["clientSecret"] = o.ClientSecret
	toSerialize["tenantID"] = o.TenantID
	toSerialize["subscriptionID"] = o.SubscriptionID
	toSerialize["baseGroupName"] = o.BaseGroupName
	return toSerialize, nil
}

type NullableAzureAccountConfig struct {
	value *AzureAccountConfig
	isSet bool
}

func (v NullableAzureAccountConfig) Get() *AzureAccountConfig {
	return v.value
}

func (v *NullableAzureAccountConfig) Set(val *AzureAccountConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureAccountConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureAccountConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureAccountConfig(val *AzureAccountConfig) *NullableAzureAccountConfig {
	return &NullableAzureAccountConfig{value: val, isSet: true}
}

func (v NullableAzureAccountConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureAccountConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
