inputSpec: https://api.redocly.com/registry/bundle/curvegrid/multibaas/v0/openapi.yaml
outputDir: .
generatorName: go
gitUserId: curvegrid
gitRepoId: multibaas-sdk-go
packageVersion: 1.0.0-beta2
packageName: multibaas
additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: true
  useOneOfDiscriminatorLookup: true
  generateInterfaces: true
