inputSpec: https://api.redocly.com/registry/bundle/curvegrid/multibaas/v0/openapi.yaml
outputDir: .
generatorName: go
gitUserId: curvegrid
gitRepoId: multibaas-sdk-go
packageVersion: 1.0.3
packageName: multibaas
modelNameMappings:
  APIKey: ApiKey # Fix collision with openapi-generator APIKey struct in configuration.go
additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: true
  useOneOfDiscriminatorLookup: true
  generateInterfaces: true
